name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run database migrations (if any scripts are available)
    - name: Run database migrations
      run: |
        echo "Skipping migrations if not needed."
        # Uncomment and add migration command if needed.
        # python migration_script.py

    # Step 5: Start Gunicorn
    - name: Start Gunicorn server
      run: |
        gunicorn app.main:app --bind 0.0.0.0:8000 --workers 4 &
        sleep 10  # Give Gunicorn some time to start

    # Step 6: Run API tests
    - name: Run tests
      run: |
        # python test.py

    # Step 7: Stop Gunicorn process
    - name: Stop Gunicorn
      run: |
        pkill -f gunicorn
